### ISSUE TITLE
satis workflow fails

### ISSUE THREAD

**Issue by midahp** [maintaina-com/Ldap#4]
failed run: https://github.com/maintaina-com/Ldap/actions/runs/3240224900/jobs/5311050399#step:8:507

error output:
```
Selected horde/ldap (dev-master)

Error: trim() expects parameter 1 to be string, int given
In ArrayLoader.php line 212:
                                                      
  [TypeError]                                         
  trim() expects parameter 1 to be string, int given  
                                                      

Exception trace:
  at /home/runner/work/Ldap/Ldap/satis/vendor/composer/composer/src/Composer/Package/Loader/ArrayLoader.php:212
 trim() at /home/runner/work/Ldap/Ldap/satis/vendor/composer/composer/src/Composer/Package/Loader/ArrayLoader.php:212
 Composer\Package\Loader\ArrayLoader->configureObject() at /home/runner/work/Ldap/Ldap/satis/vendor/composer/composer/src/Composer/Package/Loader/ArrayLoader.php:72
 Composer\Package\Loader\ArrayLoader->load() at /home/runner/work/Ldap/Ldap/satis/src/PackageSelection/PackageSelection.php:324
 Composer\Satis\PackageSelection\PackageSelection->load() at /home/runner/work/Ldap/Ldap/satis/src/Console/Command/BuildCommand.php:235
 Composer\Satis\Console\Command\BuildCommand->execute() at /home/runner/work/Ldap/Ldap/satis/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /home/runner/work/Ldap/Ldap/satis/vendor/symfony/console/Application.php:1028
 Symfony\Component\Console\Application->doRunCommand() at /home/runner/work/Ldap/Ldap/satis/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /home/runner/work/Ldap/Ldap/satis/vendor/composer/composer/src/Composer/Console/Application.php:370
 Composer\Console\Application->doRun() at /home/runner/work/Ldap/Ldap/satis/src/Console/Application.php:60
 Composer\Satis\Console\Application->doRun() at /home/runner/work/Ldap/Ldap/satis/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /home/runner/work/Ldap/Ldap/satis/vendor/composer/composer/src/Composer/Console/Application.php:138
 Composer\Console\Application->run() at /home/runner/work/Ldap/Ldap/satis/bin/satis:71

build [--repository-url REPOSITORY-URL] [--repository-strict] [--no-html-output] [--skip-errors] [--stats] [--minify] [--] [<file> [<output-dir> [<packages>...]]]
```

**Comment by midahp** [comment]
same issue for horde/perms: https://github.com/maintaina-com/Perms/actions/runs/3240250595/jobs/5310651809#step:8:510

and horde/queue: https://github.com/maintaina-com/Queue/actions/runs/3240314004/jobs/5310792451#step:8:338

**Comment by ralflang** [comment]
Yes, I already spotted that one. 
The reason is a malformed suggests clause that should be a string but is an int. 
I have a pending patch for composer/composer (PR in lunch break I guess).

**Comment by ralflang** [comment]
See composer/composer#11117

**Comment by midahp** [comment]
thank you for the PR. Lets see if it will actually be merged.

I tried to find an integer in the 'suggest' field in the composer.json of a tag/branch of ldap & queue. I could not find anything. It seems like the issue is not in these packages but rather in https://github.com/maintaina-com/components/blob/v1.0.0alpha2/composer.json

Satis/Composer goes through dependencies recursively it seems. Can we delete that tag and try again?

**Comment by ralflang** [comment]
Considering the age of the tag I am fine with that approach. Before exhausting your rate limit, ensure it's not also in neighbouring tags :(

**Comment by midahp** [comment]
I deleted it. But it still shows me the error. I already tried composer clear-cache.

It also shows me an error for `1.0.0.0-alpha3` in horde/components which does not seem to be a tag. The commit sha error occurs for is `19d13bb3f2165cb9924e2aef09d5c7121d90435f`  and https://github.com/maintaina-com/components/commit/19d13bb3f2165cb9924e2aef09d5c7121d90435f does show the integer in the composer.json but it seems to be tagged with `1.0.0alpha4`. But https://github.com/maintaina-com/components/blob/v1.0.0alpha4/composer.json does not have the integer in the composer.json. 

This is all very confusing...

**Comment by ralflang** [comment]
I am doing some tests to identify this. I think this is caused by PEAR pecl deplarations like this:

```   
 [pear-pecl.php.net/intl] => Array
        (
            [version] => *
            [providesextension] => intl
        )
```


The components tool will likely need an upgrade.
- Version constraints containing "*" or '*' need to be represented in JSON as * only.
- Improved handling of "suggests". I will come up with something that does not break on existing yaml.

**Comment by ralflang** [comment]
horde/mime is one of the culprits.
